services:

  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
      - database
    networks:
      - nginx-php81-mysql8
  php81-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php81-container
    environment:
      DATABASE_URL: "mysql://user:password@database:3306/main?serverVersion=5.7"
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php81-mysql8
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - nginx-php81-mysql8
networks:
  nginx-php81-mysql8: